### ISSUE TITLE
hologram-boot process uses 60%+ CPU on macOS Sierra

### ISSUE THREAD

**Issue by dansteeves68** [AdRoll/hologram#88]
I'm just a user of `hologram me`, not a developer. My colleagues have been distributing hologram and it works pretty well. However as a Mac user I've had some issues that don't get any attention. This seems to be the only place to ask some questions...

- Occasionally I will find my laptop fan running and when I check Activity Monitor I find hologram-boot is using a ton of CPU. Is that a known bug?
- Why is hologram-anything running when I've not used `hologram me` or anything else since a reboot? Can I make that stop?
- How do I uninstall everything hologram? My colleagues have only distributed an installer package.

Thanks. Sorry for polluting the "issues" log like this.

<img width="565" alt="screenshot 2017-03-18 06 56 35" src="https://cloud.githubusercontent.com/assets/1696420/24071849/b1c04a0a-0ba9-11e7-83f4-908a4f40167b.png">

**Comment by walterking** [comment]
No need to apologize, this is the right place for this.

Occasionally I will find my laptop fan running and when I check Activity Monitor I find hologram-boot is using a ton of CPU. Is that a known bug?
I've never seen this before, and most users i know are mac users.  Hologram-boot just logs you in automatically on startup, but if hologram-agent isnt working it looks like it never quits.  I wouldnt expect it to take this much CPU.  There should be logs in /var/log/system.log, and /var/log/hologram.log.  If you could share them or errors in them it might be helpful.  Specifically, I think hologram-agent isn't starting correctly, which logs to hologram.log, and if we can figure out why then it should solve the cpu.

Why is hologram-anything running when I've not used hologram me or anything else since a reboot? Can I make that stop?
Generally, we access hologram frequently enough that its easier for us to default to running and logged in than have to turn it on every boot.  Also, the agent that gives the actual credentials out needs superuser privileges to open a http port, and alias network devices, and it's easier to start that at boot than asking a user to sudo sometimes.  Theres not a great way to stop it.  You can remove /Library/LaunchDaemons/com.adroll.hologram-me.plist, which will prevent hologram-boot from running, at startup, requiring you to `hologram me` before it functions, but preventing the agent to start would lead to a bad experience whenever you did need to use it. 

How do I uninstall everything hologram? My colleagues have only distributed an installer package.
There isnt an uninstaller if i understand pkg correctly, you'd have to delete files manually.  
`rm /usr/local/bin/hologram*`
`rm /Library/Launch{Agent,Daemon}/com.adroll.hologram*`
should remove the files.  But this is _untested_ so ymmv

**Comment by dansteeves68** [comment]
I took a look at the logs and I'll give you a bit of background before you look at them. (I sent the system.log file I think is relevant for the CPU race I had on the morning of 03-18.)

- The group I work in uses OpenVPN, which I run using Viscosity.app. I don't connect automatically. If I'm not connected I don't have access to the LDAP server that I need for `hologram me`.
- The parent company uses a god-forsaken Cisco VPN for which I don't currently have a solution besides the Cisco AnyConnect client. The acvpnagent logs a bunch of garbage to system.log that I have not been able to do anything about.
- I notice hologram logging that a port is in use. The proprietary platform that I work on has a couple of services that pick a random-ish port to bind to on startup. But those services don't start on boot so hologram should always have a relatively normal Mac to boot in.

[system.log.1.gz](https://github.com/AdRoll/hologram/files/854469/system.log.1.gz)
[hologram.log.gz](https://github.com/AdRoll/hologram/files/854470/hologram.log.gz)

**Comment by walterking** [comment]
The VPN is similar to our setups, though not that particular software.  It shouldn't interfere unless you run hologram commands or try to pull credentials from the metadata service, in which case you get timeouts/errors, but not this behavior.  

The port it binds to is 169.254.169.254:80, so only on that IP address, so its extremely unlikely any other service will interfere.  

The port in use error is the unix socket, so the only other thing it would interfere with is another hologram agent.

I see errors failing to connect to your hologram server, but that should be ok.  
```
runtime stack:
runtime.MSpanList_Insert(0x5a5b08, 0x622dd0)
        /usr/src/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_AllocStack(0x5a5960, 0x4, 0x1)
        /usr/src/go/src/runtime/mheap.c:267 +0x71```

https://github.com/golang/go/issues/17335 seems to suggest this is a go issue, and building with a newer golang will prevent that.  Maybe see if you can get a new pkg built with a newer version of golang?

**Comment by dansteeves68** [comment]
Thanks. I've asked for a newer golang build.

I did not try to remove anything yet, but in searching for some of those files you mentioned I came across some diagnostic reports for my CPU events. :-).

    $ sudo find /Library -name "*hologram*"
    /Library/LaunchDaemons/com.adroll.hologram-ip.plist
    /Library/LaunchDaemons/com.adroll.hologram-me.plist
    /Library/LaunchDaemons/com.adroll.hologram.plist
    /Library/Logs/DiagnosticReports/hologram-boot_2017-02-20-173428_glycerine.cpu_resource.diag
    /Library/Logs/DiagnosticReports/hologram-boot_2017-02-21-161840_glycerine.cpu_resource.diag
    /Library/Logs/DiagnosticReports/hologram-boot_2017-02-27-083252_glycerine.cpu_resource.diag
    /Library/Logs/DiagnosticReports/hologram-boot_2017-02-28-073224_glycerine.cpu_resource.diag
    /Library/Logs/DiagnosticReports/hologram-boot_2017-03-02-155947_glycerine.cpu_resource.diag
    /Library/Logs/DiagnosticReports/hologram-boot_2017-03-17-201908_glycerine.cpu_resource.diag

**Comment by dansteeves68** [comment]
Well, since I got a new build I have now found one more report.
[hologram-boot_2017-04-06-212019_glycerine.cpu_resource.diag.txt](https://github.com/AdRoll/hologram/files/922504/hologram-boot_2017-04-06-212019_glycerine.cpu_resource.diag.txt)

**Comment by dansteeves68** [comment]
No longer important.
